# Generated by Django 4.1.7 on 2023-03-04 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_taginfo_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginfo',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
