# Generated by Django 4.1.7 on 2023-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_taginfo_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginfo',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='taginfo',
            name='tag_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
