# Generated by Django 4.1.7 on 2023-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
