# Generated by Django 4.1.7 on 2023-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image_alter_product_sold_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('S', 'Sold'), ('K', 'Kicked Back'), ('D', 'Denied')], max_length=1),
        ),
    ]
