# Generated by Django 4.1.7 on 2023-03-04 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginfo',
            name='date_added',
            field=models.DateField(verbose_name=datetime.datetime(2023, 3, 4, 16, 35, 20, 21146)),
        ),
    ]
