# Generated by Django 4.1.7 on 2023-03-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_taginfo_product_name_taginfo_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taginfo',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='taginfo',
            name='tag_name',
        ),
    ]
